name: update website
on:
- push
- pull_request
jobs:
  processData:
    runs-on: ubuntu-20.04
    name: process data file
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.14.2
      uses: actions/setup-node@v1
      with:
         node-version: 16.14.2
    - name: npm install, start process
      run: |
        cd ./src/data
        npm install
        node processData.js
    - name: commit
      run: |
        git config user.name "Github Actions Bot - processData"
        git config user.email "<>"
        git add .
        git commit -m "[Bot] Auto process data files"
        git push origin main
  
  deploy:
    name: deploy to Tencent COS
    needs: processData
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          CI: false
          NODE_ENV: production
          GENERATE_SOURCEMAP: false
      - name: Upload COS
        uses: Bluefissure/tencent-cos-action@v0.1.1
        with:
          args: upload -rs ./build/ /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-guangzhou
          accelerate: false